CREATE TABLE IF NOT EXISTS tb_usuarios ( 

idUsuario BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
sobrenome VARCHAR(150) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
senha VARCHAR(20) NOT NULL
);